name: Deploy Application

on:
  push:
    branches:
      - main  # Ou a branch que deseja monitorar para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use a versão do Node.js que seu projeto requer

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start SSH agent and add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.FRONTEND_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "145.223.27.56 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3BEdtNj8S7/5gPq8eb30xIwCufns48SuKg4aH7D/bBRRIrIhKZfBApYBRwDMT0+IDRW2kn/JthHN5GCcxcCV9XcNAfh5L5djoywUeBl+LPxqUwlL+LkM7sKESxTUCnpWX6aX6CHdkIPbXoP4goU+w3S+hjtAGxeqMVe0YX8OFFjTCN7SJLgbmTPZh+dRHZ4LqjQKP5EHeGN6jlHT5Le7mo25r5u+AcQCLBcMOPvEOUH95doZFzeD770s9VJW6MiOnMBzAa2JzqW7hfXKt7vw6zT9NB0YsP5eVl0WjOCchlDTrjmZOEF3HHZ7P4gNNEatE2SzBWgGo+HHkRREk6gsxL5NIjkHpzqQKnmigTSNr/sfBSLNXxpBF7O13RsQdbiPTA5mCWQi8fVK3AS4VP4boC32NvzNclSuI2gQO0CNS7V3RmqMqoZHhnJV50qI0f2IFp7gVaPO0gsAKhLJq9mRrHAFCcXpkkfX7/2H1+2jdhE+8cQX7tBm2fNXt0hdPqPU=" >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: rsync -avz --exclude '.git' ./ solar_front@145.223.27.56:/home/user-solar/htdocs/app.cooperativasolarman.com.br
